name: Deploy app to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Copy files to server
      run: scp -r dist rens@83.82.4.97:/var/www/html
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Restart server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 83.82.4.97
        username: rens
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: 'sudo service nginx restart'
